CPPFLAGS=-I/usr/include/freetype2 -I/usr/include/SDL -D_DESKTOP_
LIBS=-lGL -lfreetype -lSDL -lboost_system -lboost_filesystem -lfreeimage -lSDL_mixer
ADDITIONAL_SRC_SOURCES=Renderer_init_sdlgl.cpp

include Makefile.common
