//this file was auto-generated by res2h

#include "Resources.h"

const size_t res2hNrOfFiles = 10;
const Res2hEntry res2hFiles[res2hNrOfFiles] = {
    {":/bar.png", bar_png_size, bar_png_data},
    {":/button.png", button_png_size, button_png_data},
    {":/corner.png", corner_png_size, corner_png_data},
    {":/ES_logo_16.png", ES_logo_16_png_size, ES_logo_16_png_data},
    {":/ES_logo_32.png", ES_logo_32_png_size, ES_logo_32_png_data},
    {":/frame.png", frame_png_size, frame_png_data},
    {":/glow_hor.png", glow_hor_png_size, glow_hor_png_data},
    {":/glow_off_hor.png", glow_off_hor_png_size, glow_off_hor_png_data},
    {":/glow_off_vert.png", glow_off_vert_png_size, glow_off_vert_png_data},
    {":/glow_vert.png", glow_vert_png_size, glow_vert_png_data}
};

res2hMapType::value_type mapTemp[] = {
    std::make_pair(":/bar.png", res2hFiles[0]),
    std::make_pair(":/button.png", res2hFiles[1]),
    std::make_pair(":/corner.png", res2hFiles[2]),
    std::make_pair(":/ES_logo_16.png", res2hFiles[3]),
    std::make_pair(":/ES_logo_32.png", res2hFiles[4]),
    std::make_pair(":/frame.png", res2hFiles[5]),
    std::make_pair(":/glow_hor.png", res2hFiles[6]),
    std::make_pair(":/glow_off_hor.png", res2hFiles[7]),
    std::make_pair(":/glow_off_vert.png", res2hFiles[8]),
    std::make_pair(":/glow_vert.png", res2hFiles[9])
};

res2hMapType res2hMap(mapTemp, mapTemp + sizeof mapTemp / sizeof mapTemp[0]);
