//this file was auto-generated by res2h

#include "Resources.h"

const size_t res2hNrOfFiles = 22;
const Res2hEntry res2hFiles[res2hNrOfFiles] = {
    {":/arrow.png", arrow_png_size, arrow_png_data},
    {":/button.png", button_png_size, button_png_data},
    {":/button_filled.png", button_filled_png_size, button_filled_png_data},
    {":/checkbox_checked.png", checkbox_checked_png_size, checkbox_checked_png_data},
    {":/checkbox_unchecked.png", checkbox_unchecked_png_size, checkbox_unchecked_png_data},
    {":/ES_logo_16.png", ES_logo_16_png_size, ES_logo_16_png_data},
    {":/ES_logo_32.png", ES_logo_32_png_size, ES_logo_32_png_data},
    {":/frame.png", frame_png_size, frame_png_data},
    {":/opensans_hebrew_condensed_regular.ttf", opensans_hebrew_condensed_regular_ttf_size, opensans_hebrew_condensed_regular_ttf_data},
    {":/scroll_gradient.png", scroll_gradient_png_size, scroll_gradient_png_data},
    {":/slider_knob.png", slider_knob_png_size, slider_knob_png_data},
    {":/sq_bracket.png", sq_bracket_png_size, sq_bracket_png_data},
    {":/star_filled.png", star_filled_png_size, star_filled_png_data},
    {":/star_unfilled.png", star_unfilled_png_size, star_unfilled_png_data},
    {":/textbox.png", textbox_png_size, textbox_png_data},
    {":/textbox_glow.png", textbox_glow_png_size, textbox_glow_png_data},
    {":/help/a.png", help_a_png_size, help_a_png_data},
    {":/help/b.png", help_b_png_size, help_b_png_data},
    {":/help/dpad.png", help_dpad_png_size, help_dpad_png_data},
    {":/help/left_right.png", help_left_right_png_size, help_left_right_png_data},
    {":/help/menu.png", help_menu_png_size, help_menu_png_data},
    {":/help/up_down.png", help_up_down_png_size, help_up_down_png_data}
};

res2hMapType::value_type mapTemp[] = {
    std::make_pair(":/arrow.png", res2hFiles[0]),
    std::make_pair(":/button.png", res2hFiles[1]),
    std::make_pair(":/button_filled.png", res2hFiles[2]),
    std::make_pair(":/checkbox_checked.png", res2hFiles[3]),
    std::make_pair(":/checkbox_unchecked.png", res2hFiles[4]),
    std::make_pair(":/ES_logo_16.png", res2hFiles[5]),
    std::make_pair(":/ES_logo_32.png", res2hFiles[6]),
    std::make_pair(":/frame.png", res2hFiles[7]),
    std::make_pair(":/opensans_hebrew_condensed_regular.ttf", res2hFiles[8]),
    std::make_pair(":/scroll_gradient.png", res2hFiles[9]),
    std::make_pair(":/slider_knob.png", res2hFiles[10]),
    std::make_pair(":/sq_bracket.png", res2hFiles[11]),
    std::make_pair(":/star_filled.png", res2hFiles[12]),
    std::make_pair(":/star_unfilled.png", res2hFiles[13]),
    std::make_pair(":/textbox.png", res2hFiles[14]),
    std::make_pair(":/textbox_glow.png", res2hFiles[15]),
    std::make_pair(":/help/a.png", res2hFiles[16]),
    std::make_pair(":/help/b.png", res2hFiles[17]),
    std::make_pair(":/help/dpad.png", res2hFiles[18]),
    std::make_pair(":/help/left_right.png", res2hFiles[19]),
    std::make_pair(":/help/menu.png", res2hFiles[20]),
    std::make_pair(":/help/up_down.png", res2hFiles[21])
};

res2hMapType res2hMap(mapTemp, mapTemp + sizeof mapTemp / sizeof mapTemp[0]);
