//this file was auto-generated by res2h

#pragma once

#include <string>
#include <map>

extern const size_t bar_png_size;
extern const unsigned char bar_png_data[];

extern const size_t button_png_size;
extern const unsigned char button_png_data[];

extern const size_t corner_png_size;
extern const unsigned char corner_png_data[];

extern const size_t ES_logo_16_png_size;
extern const unsigned char ES_logo_16_png_data[];

extern const size_t ES_logo_32_png_size;
extern const unsigned char ES_logo_32_png_data[];

extern const size_t frame_png_size;
extern const unsigned char frame_png_data[];

extern const size_t glow_hor_png_size;
extern const unsigned char glow_hor_png_data[];

extern const size_t glow_off_hor_png_size;
extern const unsigned char glow_off_hor_png_data[];

extern const size_t glow_off_vert_png_size;
extern const unsigned char glow_off_vert_png_data[];

extern const size_t glow_vert_png_size;
extern const unsigned char glow_vert_png_data[];

struct Res2hEntry {
    const std::string relativeFileName;
    const size_t size;
    const unsigned char * data;
};

extern const size_t res2hNrOfFiles;
extern const Res2hEntry res2hFiles[];

typedef const std::map<const std::string, const Res2hEntry> res2hMapType;
extern res2hMapType res2hMap;
