// this file was auto-generated by res2h

#pragma once

#include <string>
#include <map>

extern const uint16_t splash_svg_size;
extern const uint8_t splash_svg_data[];

extern const uint16_t opensans_hebrew_condensed_light_ttf_size;
extern const uint8_t opensans_hebrew_condensed_light_ttf_data[];

extern const uint16_t frame_png_size;
extern const uint8_t frame_png_data[];

extern const uint16_t textinput_ninepatch_active_png_size;
extern const uint8_t textinput_ninepatch_active_png_data[];

extern const uint16_t window_icon_256_png_size;
extern const uint8_t window_icon_256_png_data[];

extern const uint16_t slider_knob_svg_size;
extern const uint8_t slider_knob_svg_data[];

extern const uint16_t fav_remove_svg_size;
extern const uint8_t fav_remove_svg_data[];

extern const uint16_t off_svg_size;
extern const uint8_t off_svg_data[];

extern const uint16_t fav_add_svg_size;
extern const uint8_t fav_add_svg_data[];

extern const uint16_t star_filled_svg_size;
extern const uint8_t star_filled_svg_data[];

extern const uint16_t busy_0_svg_size;
extern const uint8_t busy_0_svg_data[];

extern const uint16_t checkbox_unchecked_svg_size;
extern const uint8_t checkbox_unchecked_svg_data[];

extern const uint16_t busy_3_svg_size;
extern const uint8_t busy_3_svg_data[];

extern const uint16_t textinput_ninepatch_png_size;
extern const uint8_t textinput_ninepatch_png_data[];

extern const uint16_t button_filled_png_size;
extern const uint8_t button_filled_png_data[];

extern const uint16_t option_arrow_svg_size;
extern const uint8_t option_arrow_svg_data[];

extern const uint16_t busy_1_svg_size;
extern const uint8_t busy_1_svg_data[];

extern const uint16_t checkbox_checked_svg_size;
extern const uint8_t checkbox_checked_svg_data[];

extern const uint16_t opensans_hebrew_condensed_regular_ttf_size;
extern const uint8_t opensans_hebrew_condensed_regular_ttf_data[];

extern const uint16_t star_unfilled_svg_size;
extern const uint8_t star_unfilled_svg_data[];

extern const uint16_t busy_2_svg_size;
extern const uint8_t busy_2_svg_data[];

extern const uint16_t on_svg_size;
extern const uint8_t on_svg_data[];

extern const uint16_t button_png_size;
extern const uint8_t button_png_data[];

extern const uint16_t arrow_svg_size;
extern const uint8_t arrow_svg_data[];

extern const uint32_t scroll_gradient_png_size;
extern const uint8_t scroll_gradient_png_data[];

extern const uint16_t help__analog_thumb_svg_size;
extern const uint8_t help__analog_thumb_svg_data[];

extern const uint16_t help__button_x_svg_size;
extern const uint8_t help__button_x_svg_data[];

extern const uint16_t help__dpad_leftright_svg_size;
extern const uint8_t help__dpad_leftright_svg_data[];

extern const uint16_t help__dpad_right_svg_size;
extern const uint8_t help__dpad_right_svg_data[];

extern const uint16_t help__dpad_down_svg_size;
extern const uint8_t help__dpad_down_svg_data[];

extern const uint16_t help__button_y_svg_size;
extern const uint8_t help__button_y_svg_data[];

extern const uint16_t help__analog_up_svg_size;
extern const uint8_t help__analog_up_svg_data[];

extern const uint16_t help__button_r_svg_size;
extern const uint8_t help__button_r_svg_data[];

extern const uint16_t help__button_b_svg_size;
extern const uint8_t help__button_b_svg_data[];

extern const uint16_t help__button_l_svg_size;
extern const uint8_t help__button_l_svg_data[];

extern const uint16_t help__button_hotkey_svg_size;
extern const uint8_t help__button_hotkey_svg_data[];

extern const uint16_t help__button_start_svg_size;
extern const uint8_t help__button_start_svg_data[];

extern const uint16_t help__dpad_all_svg_size;
extern const uint8_t help__dpad_all_svg_data[];

extern const uint16_t help__button_select_svg_size;
extern const uint8_t help__button_select_svg_data[];

extern const uint16_t help__dpad_up_svg_size;
extern const uint8_t help__dpad_up_svg_data[];

extern const uint16_t help__button_a_svg_size;
extern const uint8_t help__button_a_svg_data[];

extern const uint16_t help__dpad_left_svg_size;
extern const uint8_t help__dpad_left_svg_data[];

extern const uint16_t help__analog_left_svg_size;
extern const uint8_t help__analog_left_svg_data[];

extern const uint16_t help__analog_right_svg_size;
extern const uint8_t help__analog_right_svg_data[];

extern const uint16_t help__analog_down_svg_size;
extern const uint8_t help__analog_down_svg_data[];

extern const uint16_t help__dpad_updown_svg_size;
extern const uint8_t help__dpad_updown_svg_data[];

struct Res2hEntry {
    const std::string relativeFileName;
    const uint32_t size;
    const uint8_t * data;
};

extern const uint32_t res2hNrOfFiles;
extern const Res2hEntry res2hFiles[];

typedef const std::map<const std::string, const Res2hEntry> res2hMapType;
extern res2hMapType res2hMap;
