//this file was auto-generated by res2h

#include "Resources.h"

const size_t res2hNrOfFiles = 4;
const Res2hEntry res2hFiles[res2hNrOfFiles] = {
    {":/bar.png", bar_png_size, bar_png_data},
    {":/corner.png", corner_png_size, corner_png_data},
    {":/ES_logo_16.png", ES_logo_16_png_size, ES_logo_16_png_data},
    {":/ES_logo_32.png", ES_logo_32_png_size, ES_logo_32_png_data}
};

res2hMapType::value_type mapTemp[] = {
    std::make_pair(":/bar.png", res2hFiles[0]),
    std::make_pair(":/corner.png", res2hFiles[1]),
    std::make_pair(":/ES_logo_16.png", res2hFiles[2]),
    std::make_pair(":/ES_logo_32.png", res2hFiles[3])
};

res2hMapType res2hMap(mapTemp, mapTemp + sizeof mapTemp / sizeof mapTemp[0]);
