#pragma once

namespace PlatformIds
{
	enum PlatformId
	{
		PLATFORM_UNKNOWN,
		THREEDO, //can't start with a constant
		AMIGA,
		ARCADE,
		ATARI_2600,
		ATARI_5200,
		ATARI_7800,
		ATARI_JAGUAR,
		ATARI_JAGUAR_CD,
		ATARI_XE,
		COLECOVISION,
		COMMODORE_64,
		INTELLIVISION,
		MAC_OS,
		XBOX,
		XBOX_360,
		NEOGEO,
		NINTENDO_3DS,
		NINTENDO_64,
		NINTENDO_DS,
		NINTENDO_ENTERTAINMENT_SYSTEM,
		GAME_BOY,
		GAME_BOY_ADVANCE,
		GAME_BOY_COLOR,
		NINTENDO_GAMECUBE,
		NINTENDO_WII,
		NINTENDO_WII_U,
		PC,
		SEGA_32X,
		SEGA_CD,
		SEGA_DREAMCAST,
		SEGA_GAME_GEAR,
		SEGA_GENESIS,
		SEGA_MASTER_SYSTEM,
		SEGA_MEGA_DRIVE,
		SEGA_SATURN,
		PLAYSTATION,
		PLAYSTATION_2,
		PLAYSTATION_3,
		PLAYSTATION_4,
		PLAYSTATION_VITA,
		PLAYSTATION_PORTABLE,
		SUPER_NINTENDO,
		TURBOGRAFX_16,
		PLATFORM_COUNT
	};
}

